version: "3"
services:
  backend:
    build: backend/
    ports:
      - ${BACKPORT}:3000
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - DBPORT=${DBPORT}
      - ADMINLOGIN=${ADMINLOGIN}
      - ADMINPASSWORD=${ADMINPASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend/app:/app/backend
  frontend:
    build: frontend/
    ports:
      - ${FRONTPORT}:80
    links:
      - backend
    environment:
      - BACKPORT=${BACKPORT}
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
  postgres:
    image: postgres:15.2-alpine
    ports:
      - ${DBPORT}:5432
    volumes:
      - ./persistantdb/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
